name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Fetch latest CMTEB data
      run: |-
        python cmteb.py
    - name: Fetch latest ANDNET data
      run: |-
        python andnet.py    
    - name: Commit and push if it changed
      run: |-
        git config user.name "gov2-ro"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push