name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: CMTEB Termoficare București
      run: |-
        python cmteb.py
      continue-on-error: true
    - name: ANDNET Situație Drumuri map
      run: |-
        python andnet-harta.py    
      continue-on-error: true
    - name: ANDNET Situație Drumuri list
      run: |-
        python andnet-tables.py    
      continue-on-error: true
    - name: sesizări BV
      run: |-
        python brasov-sesizari.py
      continue-on-error: true
    - name: pârtii BV
      run: |-
        python stare-partii-bv.py
      continue-on-error: true
    - name: instalații BV
      run: |-
        python instalatii-partie-bv.py
      continue-on-error: true
    # - name: avarii PMB
    #   run: |-
    #     python pmb-avarii.py
    #   continue-on-error: true
    # - name: iasi calitate aer
    #   run: |-
    #     python iasi-calitate-aer.py
    #   continue-on-error: true
    - name: aerlive bucuresti
      run: |-
        python aerlive-bucuresti.py
      continue-on-error: true
    - name: aerlive cj
      run: |-
        python aerlive-cj.py
      continue-on-error: true
    - name: Trafic Frontieră map
      run: |-
        python trafic-frontiere-markers.py
      continue-on-error: true
    - name: Trafic Frontieră list
      run: |-
        python trafic-frontiere-list.py
      continue-on-error: true
    - name: Intervenții Urs (Bear Interventions)
      run: |-
        python interventii-urs.py
      continue-on-error: true
    # - name: DEER incidente
    #   run: |-
    #     python deer-incidente.py
    #   continue-on-error: true
    # - name: întreruperi distribuție e-distributie Enel
    #   run: |-
    #     python enel-intreruperi.py
    #   continue-on-error: true
    # - name: DEER întreruperi
    #   run: |-
    #     python deer-intreruperi.py
    #   continue-on-error: true
    # - name: posturi.gov.ro
    #   run: |-
    #     python posturi-fetch-index.py
    # continue-on-error: true
    - name: Commit and push if it changed
      run: |-
        git config user.name "gov2-ro"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push