name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: CMTEB Termoficare București
      run: |-
        python cmteb.py
    - name: ANDNET Situație Drumuri map
      run: |-
        python andnet-harta.py    
    - name: ANDNET Situație Drumuri list
      run: |-
        python andnet-tables.py    
    - name: Trafic Frontieră list
      run: |-
        python trafic-frontiere-list.py
    - name: Trafic Frontieră map
      run: |-
        python trafic-frontiere-markers.py
    - name: DEER incidente
      run: |-
        python deer-incidente.py
    - name: întreruperi distribuție e-distributie Enel
      run: |-
        python enel-intreruperi.py
    # - name: posturi.gov.ro
    #   run: |-
    #     python posturi-fetch-index-csv.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "gov2-ro"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push